src/posts/learn.md

Correct typo Yudkowski -> Yudkowsky

---

src/routes/+page.svelte

An alternative wording would be "how to do it safely" referring to the process of developing the systems.

Fix grammar error

---

src/lib/components/PostMeta.svelte

For reference see https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data and https://schema.org/BlogPosting
I also added the description meta tag, see https://developers.google.com/search/docs/appearance/snippet

Add Schema.org markup

---

src/posts/xrisk.md

When talking about intelligence, people can mean a variety of different things. So I tried to make clearer that we don't want to share knowledge on the term itself, and instead just want to define what we are concerned about.

Improve defintion of intelligene in xrisk.md

---

src/lib/components/custom/a.svelte
src/routes/footer.svelte

I added the external links icon to the links and also made it dependent on the font size (scaling the div doesn't work because the SVG gets a height parameter by default) + some styling.

Improve external links in text and footer

---

src/posts/mitigating-pause-failures.md

commit from a week ago that I cannot push from my local repo

mitigating-pause-failures added some countercounterarguments and changed some a little

---

package.json
pnpm-lock.yaml
src/routes/+layout.svelte

Also helps with #45
Deploy preview: https://65a57d184e619b0008502ec5--frabjous-pasca-68e1cb.netlify.app/

Distribute fonts locally for performance and privacy

---

package.json
pnpm-lock.yaml
src/posts/faq.md

Deploy preview: https://65a5cb8ae09f2500088f0b81--frabjous-pasca-68e1cb.netlify.app/faq

Update remark-toc and add table of contents to FAQ

---

src/routes/+page.svelte

Adjusted link target for take action per #75

---

src/routes/+layout.svelte

Fix navigation between markdown files

---

src/posts/risks.md

I think some sections can be a lot more subjective that what I've seen on the website or that at least I haven't seen other people talk about them (probably because they are not as important as x-risks), so others could not agree with them, so you should read them closely.
Also it could be written not very well and with a bunch of grammatical errors, so feel free to change it as you would prefer. I think it's better to have them amateurish written (and without links) than to not have them at all.

Bunch of added things to the risk page

---

src/posts/environmental.md

Written by Remmelt Ellen.
I'd love to hear some feedback about this page. It introduces a new risk and a new angle.

Environmental draft Remmelt

---

src/posts/faq.md

I was surprised to see that the FAQ page didn't link to https://pauseai.info/action anywhere?
So, I added this one!
__
There are many [things that you can do](https://pauseai.info/action). Writing a letter, going to a protest, donating some money or joining a community is not that hard! And these actions have a real impact. Even when facing the end of the world, there can still be hope and very rewarding work to do.
__

Add an FAQ for "What can I do?" -> /action

---

src/routes/quotes/data.json

- Add attribution for the image "© Roland Dobbins, https://en.wikipedia.org/wiki/Eliezer_Yudkowsky"

Update Eliezer Yudkowsky quote

---

src/posts/digital-brains.md

fix typo in digital-brains.md

---

.env
.gitignore
src/posts/action.md
src/routes/people/+page.ts

@joepio You need to rename your local `.env` file to `.env.local` before merging so it doesn't get published to Git.

Publish .env file with empty value and exclude /people from prerendering

---

src/posts/action.md

@joepio 
edit on "Action" page: changed the wording of the pareto rule for people unfamiliar with it

small edit to test

---

src/posts/action.md
src/posts/faq.md
src/routes/email-builder/+page.svelte

Action page: 
- Reorganized into related sections instead of one long list
- Reworded a few things
- Removed the "if you are convincing" sub-section, because I think people don't self-identify as convincing, and it is a repeat of other sections.
Email builder page:
- Added a link to https://www.campaignforaisafety.org/politician/#find-your-politician-here.

Mia's website suggestions

---

src/posts/unprotest.md

Added UN specific action items

Added UN specific action items

---

src/posts/events.md
src/posts/protests.md
src/routes/footer.svelte
src/routes/header.svelte

Events page luma

---

src/posts/summit.md

* divided in coming and past summits
* moved coming to the top
* polished (IMO) text about the SF summit

Some proposed changes to the Summit page

---

src/posts/action.md

Fixing issues noted by @Pato-desu yesterday. Please update by tomorrow morning - linking to this page on protest handouts.

Implementing Action Page Feedback - Try 2

---

src/posts/building-the-pause-button.md

Suggesting edits to the article

AI_supply_chain_suggested_edits

---

src/lib/airtable.ts
src/lib/components/NationalGroupItem.svelte
src/lib/components/NationalGroupsList.svelte
src/lib/stores/nationalGroups.ts
src/lib/types.ts
src/posts/national-groups.md
src/routes/api/national-groups/+server.ts
src/routes/api/people/+server.ts
src/routes/api/teams/+server.ts

https://deploy-preview-281--pauseai.netlify.app/national-groups

Add national groups component, use airtable

---

src/routes/write/+page.svelte

Removed 5 questions for the sake of speed, both for the AI and the user. Hopefully this stops timeouts in the auto-fill phase.

Removed 5 questions from api/write

---

src/routes/write/+page.svelte

A now non-existent field was being used.

Fixed a bug with the email writer demo button
